# Default initial positions for diablo_robot's ros2_control fake system

initial_positions:
  r_el: 0.0
  r_index_base: 0.0
  r_index_middle: 0.0
  r_index_tip: 0.0
  r_mid_base: 0.0
  r_mid_middle: 0.0
  r_mid_tip: 0.0
  r_sho_pitch: 0.0
  r_sho_roll: -1.25
  r_thumb_base: 0.0
  r_thumb_middle: 0.0
  r_thumb_tip: 0.0
  r_wrist: 0.0